### ISSUE TITLE
display free/used inodes

### ISSUE THREAD

**Issue by daniejstriata** [Canop/lfs#23]
Can you please add option to add a column for free/used inodes?

**Comment by Canop** [comment]
In the JSON output, why not, but is this a so frequent concern that you'd also want it in the table view ?

**Comment by daniejstriata** [comment]
only Display inodes column if I ask for it?

I run lfs as part of my motd. It would be good for me to show inodes issues to admins logging in,

**Comment by Canop** [comment]
I'll probably do it, as it's quite easy

**Comment by Canop** [comment]
Not 100% sure about the presentation but I might settle for this:

![image](https://user-images.githubusercontent.com/617006/140176439-70baf7e2-e24b-4fd3-a3d2-53d49d6fd9a3.png)

I've also tested with % but it doesn't really help IMO:

![image](https://user-images.githubusercontent.com/617006/140176567-040b856f-f8c0-4491-b683-49d216763960.png)

**Comment by Canop** [comment]
You mean your opinion would be to choose just "free inodes" and "inodes use%" ?

**Comment by daniejstriata** [comment]
Yes. I've never worried about inodes until there are none :-)

**Comment by Canop** [comment]
As you can see, it's not really my current concern:
![image](https://user-images.githubusercontent.com/617006/140177668-9d9b2f51-ec26-43b1-b1b7-ba9c8bbc9275.png)

**Comment by Canop** [comment]
In a future versions, I'll probably make it possible to finely decide what cols to display...

**Comment by Canop** [comment]
(depending on whether I have another user or not ^^)

**Comment by daniejstriata** [comment]
That example looks great. I would even drop the free inodes column.

Choosing column in future could be helpful. Maybe have a "lite" and "full" option?

full:
```

┌───┬─────┬─────────────────────────────────┬────┬────┬────┬─────────┬────┬────┬───────────┐
│ id│ dev │           filesystem            │disk│type│used│  use%   │free│size│mount point│
├───┼─────┼─────────────────────────────────┼────┼────┼────┼─────────┼────┼────┼───────────┤
│150│253:1│/dev/mapper/cl_grbl--af001l2-root│LVM │xfs │26G │59% ███  │ 18G│44G │/          │
│112│253:1│/dev/mapper/cl_grbl--af001l2-root│LVM │xfs │26G │59% ███  │ 18G│44G │/var/tmp   │
│169│253:3│/dev/mapper/cl_grbl--af001l2-home│LVM │xfs │14G │66% ███▎ │7.4G│21G │/home      │
│166│252:1│/dev/vda1                        │HDD │ext4│287M│28% █▍   │736M│1.0G│/boot      │
└───┴─────┴─────────────────────────────────┴────┴────┴────┴─────────┴────┴────┴───────────┘
```
lite:
```
┌─────────────────────────────────┬────┬────┬────┬─────────┬────┬────┬───────────┐
│             filesystem          │disk│type│used│  use%   │free│size│mount point│
├─────────────────────────────────┼────┼────┼────┼─────────┼────┼────┼───────────┤
│/dev/mapper/cl_grbl--af001l2-root│LVM │xfs │26G │59% ███  │ 18G│44G │/          │
│/dev/mapper/cl_grbl--af001l2-root│LVM │xfs │26G │59% ███  │ 18G│44G │/var/tmp   │
│/dev/mapper/cl_grbl--af001l2-home│LVM │xfs │14G │66% ███▎ │7.4G│21G │/home      │
│/dev/vda1                        │HDD │ext4│287M│28% █▍   │736M│1.0G│/boot      │
└─────────────────────────────────┴────┴────┴────┴─────────┴────┴────┴───────────┘
```

**Comment by Canop** [comment]
Let's see:

![image](https://user-images.githubusercontent.com/617006/140178762-c776827f-293a-4b10-bfc5-525e484a3ade.png)

**Comment by daniejstriata** [comment]
That looks good. What if you add the new inodes column after the use%

**Comment by Canop** [comment]
I don't want to mix parts in bytes and parts in inodes, that would be ambiguous

**Comment by Canop** [comment]
I'll go with this for now (testing with a fs without inode):

![image](https://user-images.githubusercontent.com/617006/140181466-bd5f04dc-ef36-4f51-9d5c-aa140e609065.png)

**Comment by Canop** [comment]
Released. I've spent more time than expected on the tests and small details...

**Comment by daniejstriata** [comment]
I appreciate! Thank you.
