### ISSUE TITLE
panic error when drive is full

### ISSUE THREAD

**Issue by daniejstriata** [Canop/lfs#26]
Hi,

I got this error on what I believe was a full drive.
```
thread 'main' panicked at 'index out of bounds: the len is 10 but the index is 10', /cargo/registry/src/github.com-1ecc6299db9ec823/termimad-0.17.0/src/tbl.rs:214:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Growing drive took the error away. Setting backtrace did not make any difference.

**Comment by Canop** [comment]
Were you running lfs in a very thin terminal ?

**Comment by daniejstriata** [comment]
@Canop no. It was a normal ssh session.

**Comment by Canop** [comment]
I'm puzzled there. I have no idea how this can happen.

Can you check the version of lfs you're using ?

**Comment by daniejstriata** [comment]
It is on 1.3.0. The only thing wrong here was that the one drive was full. When I grew the disk lfs worked again.

**Comment by Stargateur** [comment]
The only thing that could come to my mind to explain this with a full drive is linux not being able to correctly answer api call for the fd of the virtual console, or ssh who need to handle it but fail if disk is full for the same reason. But that a random guess.

**Comment by Canop** [comment]
The error is in Termimad. And I just notice the version of termimad included in lfs is quite old, which explains why I wasn't able to find the error. I thought I had updated the dependency but it seems I forgot.

**Comment by Canop** [comment]
@daniejstriata Please, what were the launch arguments ?

**Comment by daniejstriata** [comment]
I added the binary output.
`lfs --units binary`

**Comment by Canop** [comment]
As I removed that section of code, I declare the bug "solved".
