### ISSUE TITLE
Errors on macOS

### ISSUE THREAD

**Issue by melMass** [Canop/lfs#27]
Hi,

very interesting utility, but on macOS I have the following error

```bash
$ lfs -a
> Error reading mounts: Could not read dir "/sys/block"
```

**Comment by Canop** [comment]
I'm sorry but lfs is only available for linux at the moment. See https://github.com/Canop/lfs/issues/24

(closing as dupe but you can comment further, and reopen if you think closing was a mistake)

**Comment by Canop** [comment]
Maybe the error message should be changed to ask the user to check they're one linux ? But at this point it means they've already lost time installing it...

Suggestions welcome.

**Comment by Stargateur** [comment]
rename to `lfs_only_work_for_linus` but it's may be too much
