### ISSUE TITLE
Enhancement Suggestion -> List cifs by default

### ISSUE THREAD

**Issue by linpete-proto** [Canop/lfs#33]
Hey canop,

first -  merci beaucup for your great tool!
I hate df -H for at least 20 years...
lfs is working great (Ubuntu 20.04 here).

If i may suggest an enhancement: pls show cifs mounts by default - not just with the -a option.
That would be nice.

Keep up your work!

Greets
Pete

**Comment by lordrasmus** [comment]
same think whould apply for nfs mounts

maybe an option for all network mounts ?

**Comment by tripplehelix** [comment]
Would love network mounts to show by default

**Comment by Canop** [comment]
It's coming:
- a column to show whether it's remote
- inclusion of remote fs by default

![image](https://user-images.githubusercontent.com/617006/155885778-9405fa69-fb89-4815-af0c-894a3e64ddf1.png)

**Comment by Canop** [comment]
It's released in version 2.3.0
