### ISSUE TITLE
Add installation instructions for common Distros to README.md

### ISSUE THREAD

**Issue by aryoda** [Canop/lfs#34]
This would simplify the installation for "normal users" :-)

THX - super tool BTW!

**Comment by aryoda** [comment]
Sorry, I was blind ;-)  There is already a link to the installation doc.

Perhaps please add a **fat** headline named "Installation" above the link so that it is easier to find (visually)...

**Comment by Canop** [comment]
Where exactly was the link not visible enough ? In the readme ? In the documentation site's frontpage ?

**Comment by aryoda** [comment]
Ah, I just mean the github front page: https://github.com/Canop/lfs

BTW: lfs is getting famous in Germany/Europe :-)

https://www.heise.de/news/Alternative-zu-df-Linux-Werkzeug-lfs-ist-in-Version-2-0-0-erschienen-6517157.html

heise.de is the publisher of the best german computer magazins...

**Comment by Canop** [comment]
> Ah, I just mean the github front page

OK, I'll try to make this one clearer.

> BTW: lfs is getting famous in Germany/Europe

Thanks for the link. It's always frustrating when you look at the GH stars and you don't know where people come from.

**Comment by Canop** [comment]
I think it's done.

**Comment by Canop** [comment]
OMG the comments on that article... it's like the comments section under a tabloid article ^^

**Comment by aryoda** [comment]
Perfect, thanks a lot!

And yes, some comments are really biased and one thread was asking how to install it - which should be obvious now :-)
