### ISSUE TITLE
Raspberry 64-bit support

### ISSUE THREAD

**Issue by Nippey** [Canop/lfs#35]
Hi,

I wanted to try lfs on a RPI3B+ running 64-bit Debian.

As I didn't find a compatible binary, I wanted to compile on the RPI itself.
(I fetched the 2.0.1 release tarball)
See below error message.

Is there some ENV required for compilation? 

```
pi@piGate:~/src/lfs-2.0.1 $ cargo install --path .
error: failed to parse manifest at `/home/pi/src/lfs-2.0.1/Cargo.toml`
Caused by:
  failed to parse the `edition` key                                                               
Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

BR Nippey

**Comment by Nippey** [comment]
Sorry, I could solve myself.
I just noticed that the error is about rust itself.
My first contact with rust, btw :)

```
#Remove old version of rust
sudo apt remove rustc
#Install latest version
curl https://sh.rustup.rs -sSf | sh
```

**Comment by Canop** [comment]
@Nippey  Can you tell me what [target](https://doc.rust-lang.org/nightly/rustc/platform-support.html) you need ? I could maybe add it to the list of the ones I automatically build at each release.

**Comment by Nippey** [comment]
@Canop is that information sufficient?

```
pi@piGate:~ $ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
pi@piGate:~ $ uname -a
Linux piGateway 5.10.92-v8+ #1514 SMP PREEMPT Mon Jan 17 17:39:38 GMT 2022 aarch64 GNU/Linux
```
