### ISSUE TITLE
lfs crash with Plan9  mount points ( seen on wsl / Windows-Subsystems for Linux )

### ISSUE THREAD

**Issue by lordrasmus** [Canop/lfs#36]
RUST_BACKTRACE=1 ./target/debug/lfs -a
thread 'main' panicked at 'attempt to subtract with overflow', /home/ramin/.cargo/registry/src/github.com-1ecc6299db9ec823/lfs-core-0.8.1/src/stats.rs:67:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::panicking::panic
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
   3: lfs_core::stats::Stats::inodes_used
             at /home/ramin/.cargo/registry/src/github.com-1ecc6299db9ec823/lfs-core-0.8.1/src/stats.rs:67:9
   4: lfs_core::stats::Stats::inodes_use_share
             at /home/ramin/.cargo/registry/src/github.com-1ecc6299db9ec823/lfs-core-0.8.1/src/stats.rs:73:13
   5: lfs::table::print
             at ./src/table.rs:53:34
   6: lfs::main
             at ./src/main.rs:65:9
   7: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

i could try to debug it a bit for you

but how can i compile lfs with a git checkout of lfs-core ?

**Comment by lordrasmus** [comment]
i don't think it will be be a problem to make lfs-core compatible with wsl

it's basically a linux kernel running an vm 

i guess ist a problem with 9p mounts so it should happen on normal linux with a 9p mount to

but i will have i look at it when the lfs-core checkout is working :)

how can i enter the  miaou chat ? 
never used that

i gues ist a room on this website https://miaou.dystroy.org/rooms ?

**Comment by Canop** [comment]
The best room to speak about lfs in English is https://miaou.dystroy.org/3768

But you may wait to have something running before

**Comment by Canop** [comment]
As discussed with lordrasmus: the inodes related info given by the pseudo filesystem aren't consistent. I'll change lfs to only load size info and bypass inodes info when those info don't make sense.
