### ISSUE TITLE
custom sort

### ISSUE THREAD

**Issue by Canop** [Canop/lfs#37]
It would be quite easy to allow `lfs --sort inodes_free`, `lfs --sort mount`, etc.

I'll do it if users feel like it would be useful (comment below).

**Comment by lordrasmus** [comment]
for me it whould be nice to have a sorting option

maybe even a config file in .config/ so every user can change the default behaviour like they want

whould be interesting what other people think about that

**Comment by lemmy04** [comment]
this. repeatedly.
