### ISSUE TITLE
ramdisk incorrectly labelled as ssd

### ISSUE THREAD

**Issue by zaza42** [Canop/lfs#4]
`│26│252:0│/dev/zram0│SSD│ext2 │6.8G│4.9G│ 73%│ 1.8G│/                        │
`

**Comment by Canop** [comment]
Thanks. I'll look for a reliable way to identify them.

**Comment by Canop** [comment]
@zaza42 I don't reproduce this. How did you make/mount your ramdisk ?

**Comment by zaza42** [comment]
# mke2fs /dev/zram1
# mount /dev/zram1 /mnt/zram1

**Comment by Canop** [comment]
Does that happen when you create the ramdisk as tmpfs ?
