### ISSUE TITLE
wrong table labels?

### ISSUE THREAD

**Issue by paolobenve** [Canop/lfs#40]
I think that the "disk" and "type" labels aren't quite correct:

```
│  filesystem   │disk│type│used│  use%   │free│size│mount point      │
├───────────────┼────┼────┼────┼─────────┼────┼────┼─────────────────┤
│/dev/sda1      │HDD │ext4│252G│ 6% ▍    │3.7T│3.9T│/mnt/externaldisk│
│/dev/nvme0n1p10│SSD │ext4│ 72G│46% ██▎  │ 84G│156G│/home            │

```
I'd put "disk" -> "type", and "type" -> "file system":

```
│  filesystem   │type│file system│used│  use%   │free│size│mount point      │
├───────────────┼────┼───────────┼────┼─────────┼────┼────┼─────────────────┤
│/dev/sda1      │HDD │    ext4   │252G│ 6% ▍    │3.7T│3.9T│/mnt/externaldisk│
│/dev/nvme0n1p10│SSD │    ext4   │ 72G│46% ██▎  │ 84G│156G│/home            │

```

**Comment by Canop** [comment]
The "disk" tries to be as near as possible of a physical device type. That's why you see mentioned whether it's removable, rotative, SSD, etc.

The "type" is the type of what is listed. It's a list of filesystems, one row per filesystem.

**Comment by fow0ryl** [comment]
The label "disk" is only correct when handling with physical devices.
But i.e. if using zfs you get a bundle of many devices in one row. Maybe HDD's and SSD's cobined to one zpool.
The label "filesystem" in column 1 is quiet ususal.
I have never heard about a filesystem /dev/sda1 before. It's just a device. In zfs it could be a dataset (like a device to store files) or a zvol (a block device)
And of course column 3 should be labled "filesystem" ...
