### ISSUE TITLE
Enhancement Suggestion -> Change name to LSFS

### ISSUE THREAD

**Issue by franek4always** [Canop/lfs#48]
Like many other useful tools starting from "ls*"  (lshw, lsusb, lscpu, lspci, lsblk etc.) it could be convenient  to rename this tool to "lsfs"

**Comment by Canop** [comment]
I thought about this one. Because yes, I know that lfs is hard to google. But lsfs is also the name of an existing tool...

So if I decide to change the name, it will probably be something completely different

**Comment by ghuls** [comment]
Renaming should be reconsidered:

`lfs` is a know utility for configuring the Lustre file system used in HPC systems:
https://wiki.lustre.org/Configuring_Lustre_File_Striping

**Comment by Stargateur** [comment]
lsf ? :p
