### ISSUE TITLE
Not working under Raspberry aarch64

### ISSUE THREAD

**Issue by MartinKuhl** [Canop/lfs#50]
When I install lfs with 
sudo curl -L "https://dystroy.org/lfs/download/armv7-unknown-linux-gnueabihf/lfs" -o /usr/local/bin/lfs
OR
sudo curl -L "https://dystroy.org/lfs/download/aarch64-linux-android/lfs" -o /usr/local/bin/lfs

and modify the access rigths via sudo chmod +x /usr/local/bin/lfs
I always get the following error:

/usr/local/bin/lfs: /usr/local/bin/lfs: cannot execute binary file

Any idea?

As OS I am using RancherOD for Pi x64: https://github.com/rancher/os/releases/download/v1.5.5/rancheros-raspberry-pi64.zip

**Comment by Stargateur** [comment]
have you try install it with cargo ? If you download binary not mean for your os it will never work.

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh # https://rustup.rs/ install rust
cargo install lfs
```

**Comment by MartinKuhl** [comment]
I think I need the binary for the following arch: aarch64-unknown-linux bit I can only find aarch64-linux-android which is not working for me.

The installation via cargo is not possible on this OS:

-bash: /usr/local/bin/lfs: No such file or directory
rancher@rancheros:~$ cargo install lfs
    Updating crates.io index
  Installing lfs v2.4.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling libc v0.2.119
   Compiling memchr v2.4.1
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `syn` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lfs v2.4.0`, intermediate artifacts can be found at `/tmp/cargo-installaQZALD`

**Comment by MartinKuhl** [comment]
OK after update the apt source I was able to perform cargo install cc and after that cargo install lfs.
But then I get: 

Installed package `lfs v2.4.0` (executable `lfs`)
rancher@rancheros:~$ lfs
-bash: /usr/local/bin/lfs: No such file or directory

the same error like before

**Comment by Stargateur** [comment]
I believe this is due to your old install try, binary install by cargo in user mode should be in `~/.cargo/bin` rustup should have add it to your $PATH

**Comment by MartinKuhl** [comment]
after removing the old files and rerun: cargo install lfs -> now its working:
Thanks a lot

**Comment by Canop** [comment]
Thanks @Stargateur

**Comment by MartinKuhl** [comment]
in general, should the normal installation process (curl download of the lfs executable) work as well on the aarch64 plattform?

**Comment by Canop** [comment]
Probably but I'm not able to test. I'd welcome help here.

**Comment by MartinKuhl** [comment]
the some curl command same OS but on a x86 (x86_64-linux) plattform works like a charm. 
then I test in the Pi (armv7-unknown-linux-gnueabihf) and (aarch64-linux-android) but here I had the issue mentioned above

**Comment by MartinKuhl** [comment]
Now I have uninstalled cargo and rust but saved the compiled lfs file.
then I copied to /usr/local/bin/lfs + chmod +x /usr/local/bin/lfs and now I am able to call it by just typing: lfs.
I there a problem with the lfs file in the download section for this plattform?
