### ISSUE TITLE
release.sh relies on GNU sed behavior

### ISSUE THREAD

**Issue by dnabre** [Canop/lfs#6]
The release build script use a GNU-ism that isn't supported by BSD/posix sed. 

There's the line in the script:

`version=$(sed 's/version = "\([0-9.]\{1,\}\)"/\1/;t;d' Cargo.toml | head -1)`

Here's the error produced by FreeBSD's sed

`sed: 1: "s/version = "\([0-9.]\{ ...": undefined label ';d'
`

Using the --posix flag to gnu-sed will disable GNU extensions to test for erros.

**Comment by Canop** [comment]
This script is not intended for normal users: it only builds the distributed release archive. To build the application for your own use do `cargo install .`.

I'd be OK with the principle of a PR making the script compatible with FreeBSD but I won't invest time myself into it.

**Comment by dnabre** [comment]
> This script is not intended for normal users: it only builds the distributed release archive. To build the application for your own use do `cargo install .`.
> 
> I'd be OK with the principle of a PR making the script compatible with FreeBSD but I won't invest time myself into it.

I don't remember if I had trouble with the cargo build that lead me to discovering this. At this point the cargo build works fine FreeBSD. It doesn't work since lfs-core is explicitly Linux-specific, which is rather disappointing, looks like a cool tool. 

It is described as "linux utility", so that's fair. I'd suggest changing the unix tag to Linux though.
