### ISSUE TITLE
Include LVM devices in default list

### ISSUE THREAD

**Issue by chrysn** [Canop/lfs#7]
When LVM us used in partitioning, the disks on it don't show up any more in `lfs`:

```
$ lfs
no disk was found - try
    lfs -a
$ lfs -a
┌───┬────┬───────────────────────┬───┬───────────────┬────┬────┬────┬─────┬───────────────────────────────┐
│ id│dev │      filesystem       │dsk│     type      │size│used│use%│avail│mount point                    │
├───┼────┼───────────────────────┼───┼───────────────┼────┼────┼────┼─────┼───────────────────────────────┤
│ 29│0:25│/dev/mapper/daphne-root│   │     btrfs     │295G│238G│ 81%│  57G│/                              │
[...]
```

(Possibly the dev column is a bit too short to display the full device number here)

For comparison, `lsblk` lists those as:

```
$ lsblk
NAME            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda               8:0    0 298.1G  0 disk 
└─sda2            8:2    0 288.8G  0 part 
  └─daphne-root 254:0    0 274.5G  0 lvm  /
```

**Comment by Canop** [comment]
This should be fixed now. Can you please try with the last version ?

**Comment by chrysn** [comment]
I've tried to verify, but it appears that the latest HEAD of lfs runs into some endless loop. Reported as #13.

**Comment by chrysn** [comment]
No, the machine under test (with latest LVM) still reports "no disk was found".

lsblk output is unmodified, `lfs -a` output is now:

```
┌───┬────┬───────────────────────┬────┬───────────────┬────┬─────────┬─────┬────┬────────────────────────┐
│ id│dev │      filesystem       │disk│     type      │used│  use%   │avail│size│mount point             │
├───┼────┼───────────────────────┼────┼───────────────┼────┼─────────┼─────┼────┼────────────────────────┤
│ 29│0:25│/dev/mapper/daphne-root│    │     btrfs     │278G│94% ████▊│  17G│295G│/                       │
│ 30│0:27│tmpfs                  │    │     tmpfs     │   0│ 0%      │ 1.7G│1.7G│/dev/shm                │
│ 24│0:5 │udev                   │    │   devtmpfs    │   0│ 0%      │ 1.7G│1.7G│/dev                    │
│ 26│0:23│tmpfs                  │    │     tmpfs     │1.4M│ 0%      │ 348M│350M│/run                    │
│491│0:40│tmpfs                  │    │     tmpfs     │ 61K│ 0%      │ 350M│350M│/run/user/1001          │
│345│0:38│tmpfs                  │    │     tmpfs     │ 57K│ 0%      │ 350M│350M│/run/user/1000          │
│ 31│0:28│tmpfs                  │    │     tmpfs     │4096│ 0%      │ 5.2M│5.2M│/run/lock               │
│ 22│0:20│sysfs                  │    │     sysfs     │    │         │     │    │/sys                    │
│ 23│0:21│proc                   │    │     proc      │    │         │     │    │/proc                   │
│ 25│0:22│devpts                 │    │    devpts     │    │         │     │    │/dev/pts                │
│ 28│0:6 │securityfs             │    │  securityfs   │    │         │     │    │/sys/kernel/security    │
│ 32│0:29│cgroup2                │    │    cgroup2    │    │         │     │    │/sys/fs/cgroup          │
│ 33│0:30│pstore                 │    │    pstore     │    │         │     │    │/sys/fs/pstore          │
│ 34│0:31│none                   │    │      bpf      │    │         │     │    │/sys/fs/bpf             │
│ 35│0:32│systemd-1              │    │    autofs     │    │         │     │    │/proc/sys/fs/binfmt_misc│
│ 36│0:33│hugetlbfs              │    │   hugetlbfs   │    │         │     │    │/dev/hugepages          │
│ 37│0:11│tracefs                │    │    tracefs    │    │         │     │    │/sys/kernel/tracing     │
│ 38│0:7 │debugfs                │    │    debugfs    │    │         │     │    │/sys/kernel/debug       │
│ 39│0:19│mqueue                 │    │    mqueue     │    │         │     │    │/dev/mqueue             │
│ 40│0:34│configfs               │    │   configfs    │    │         │     │    │/sys/kernel/config      │
│ 41│0:35│fusectl                │    │    fusectl    │    │         │     │    │/sys/fs/fuse/connections│
│ 84│0:36│binfmt_misc            │    │  binfmt_misc  │    │         │     │    │/proc/sys/fs/binfmt_misc│
│511│0:41│gvfsd-fuse             │    │fuse.gvfsd-fuse│    │         │     │    │/run/user/1001/gvfs     │
└───┴────┴───────────────────────┴────┴───────────────┴────┴─────────┴─────┴────┴────────────────────────┘
```

**Comment by Canop** [comment]
Ok, thanks for the test.

I guess I can't avoid installing lvm on my computer now, to go further.

**Comment by chrysn** [comment]
Is there any verbose output I can give you to make things debuggable more easily, JSON output for example?

(Not that I wouldn't recommend LVM for most systems anyway, and it's probably good to have tests, but still it's an effort that may be avoidable at this time).

**Comment by chrysn** [comment]
I'm attaching a tar ball of what I think would be the relevant /sys subset; I believe this contains no personal data.

Tar ball created using `sudo tar czf /tmp/daphne-sys.tar.
[daphne-sys.tar.gz](https://github.com/Canop/lfs/files/6748082/daphne-sys.tar.gz)
gz /sys/block /sys/devices/{virtual/block,pci0000:00/0000:00:11.0/ata*}` based on introspection of /sys/block. There's a few errors flying (the obvious "permission denied" trying to read from files that are write-only, but also "File shrank by ... padding with zeroes" as tar first stats and then reads, and a few read errors in autosuspend and buffer files). Let's see if that helps; maybe it could be generalized into some general debugging guidance.

(Now not a .tgz but .tar.gz due to the stupid file extension based rules of GitHub ... whoever bases their system security on file extensions still in 2021 has only themselves to blame.)

**Comment by chrysn** [comment]
Now as `sudo tar czf /tmp/daphne-sys.tgz /proc/self/mountinfo /sys/block /sys/devices/{virtual/block,pci0000:00/0000:00:11.0/ata*}` (including mountinfo):

[daphne-sys.tar.gz](https://github.com/Canop/lfs/files/6750006/daphne-sys.tar.gz)

**Comment by Canop** [comment]
@chrysn the proc/self/mountinfo in your archive appears to be empty

**Comment by chrysn** [comment]
Good results in -a mode from all my systems now. Thanks a lot!

**Comment by Canop** [comment]
only with `-a` ?

**Comment by chrysn** [comment]
Sorry, mistyped: in non-"-a" (i.e. default) mode; -a mode has always
been good.

**Comment by Canop** [comment]
Good. I'll do a release, then.
